### PR TITLE
Move packages into subdirectories corresponding to their name

### PR DESCRIPTION
**Pull request by rustybird**
Tons of renames, but `git log --find-renames` gets everything right.

### CODE REVIEW

**Comment by rustybird** [comment]
Incorporates PR #7, ugh. Is there a better way to depend on another PR?

**Comment by marmarek** [comment]
I don't think so...

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rustybird** [comment]
If you haven't found the time to start reviewing these commits yet, can just I close the PRs and open a new one? I have even more commits that I could rebase and squash to make the whole series easier to read.

OTOH, if you _have_ already looked at some, I would add on top of them so as not to undo your mental labor.

**Comment by marmarek** [comment]
I haven't reviewed it yet. Didn't want to make conflict with QSB #21.
So, if you want to change it, close this one and open new one, based on
current master branch.

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Pull request closed without merging**
