### PR TITLE
PCR sanity check

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
Force pushed a small change to the error message: https://github.com/QubesOS/qubes-issues/issues/2569#issuecomment-272510445

**Comment by marmarek** [comment]
How does it work? Will the message be visible when prompting for LUKS passphrase, or will the whole boot process fail?

**Comment by rustybird** [comment]
The former.

**Comment by rustybird** [comment]
Force pushed a better approach: https://github.com/QubesOS/qubes-issues/issues/2569#issuecomment-272702818

**Pull request merged**
