### PR TITLE
improve wording of password setup

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by adrelanos** [comment]
I know where you are coming from. TPM has "default passwords". However, from a user perspective "You may want to use non-default password" sounds confusing.

**Comment by rustybird** [comment]
Indeed. Note that the README in @phagara's AEM4 tree avoids the confusing "default SRK password" language: https://github.com/phagara/qubes-antievilmaid/blob/6cd137acf9308ef1d19b704c7c904082946c4826/anti-evil-maid/README#L54-L65

**Comment by adrelanos** [comment]
Didn't see that before. The new wording still focuses on the negative, on no password by default.

> The SRK password can be set up by NOT passing the "-z" option

I don't think we should make "no password" the normal. The normal should be using a password. And if someone wants to optionally weaken security, they are free to do so by adding an extra command line switch.

**Comment by phagara** [comment]
In the preferred AEM setup (installing on removable media) the SRK password does not add any security (especially in case of shoulder surfing).

**Comment by marmarek** [comment]
Also in preferred AEM setup, SRK password is harmful, see https://github.com/QubesOS/qubes-antievilmaid/pull/26

**Pull request closed without merging**
