### PR TITLE
Making AEM resistant against shoulder surfing and video surveillance

### PR DESCRIPTION
**Pull request by phagara**
Observing the user during early boot should not be sufficient to defeat the protection offered by Anti Evil Maid (AEM). Using time based one-time passwords instead of simple static secret text helps avoid screen observation based attacks. Installation of the improved AEM on removable media along with usage of Linux Unified Key Setup (LUKS) key files deters keyboard observation, as an attacker would also need to seize the boot media. These enhancements are then made even stronger by adding revokable TPM assisted anti-replay protection for AEM secrets.

Support for png image static secrets was, after a [brief discussion on qubes-devel mailing list](https://groups.google.com/d/topic/qubes-devel/PsTA-3m0xA0/discussion), dropped. This vastly simplified the resulting code, while the new features introduced in this PR should serve as an adequate replacement.

The AEM installation process was simplified by automating some of the previously manual steps. Readme was enhanced with compromise recovery guides.

https://github.com/qubesOS/qubes-issues/issues/1979 should now be resolved, as the multi-factor AEM changes make use of encrypted & TPM-sealed LUKS key files.

This pull request is the product of the [Google Summer of Code project for Qubes OS](https://summerofcode.withgoogle.com/projects/#5132236411109376). For progress reports and discussion, please see the associated [qubes-devel mailing list thread](https://groups.google.com/d/topic/qubes-devel/8cAjSyg1msM/discussion) and the earier [pull request against project mentor's fork](https://github.com/rustybird/qubes-antievilmaid/pull/1) (which contains additional comments). The original [project proposal](https://github.com/phagara/gsoc2017-qubes-aem-proposal/releases/tag/user_0c97e0f1) is also still available -- although a bit outdated, as some minor alterations to the proposed implementation details were made during the coding phase of GSoC.

Many thanks to my mentor, @rustybird, for a lot of insightful comments and help with the final "few" touches to make this work ready to be submitted.

### CODE REVIEW

**Comment by rustybird** [comment]
Gee thanks GitHub, for helpfully dumping three tons of outdated commit comments here. 🙄

Anyway - as far as I can tell, Patrik's contribution is in good shape and ready to be merged (for Qubes R4, or more precisely any release with systemd >= 231 in dom0).

**Comment by phagara** [comment]
> for Qubes R4, or more precisely any release with systemd >= 231 in dom0

Plus, the `coreutils` package must contain `base32` binary -- fc23 used in Qubes R3.2 does not have that, fc25 in R4rc1 does (not sure about the exact minimum package version required).

**Comment by rustybird** [comment]
Yes indeed. It's in coreutils >= 8.25.

**Comment by rustybird** [comment]
Sorry, can you force push a change to [`coreutils >= 8.25-2`](https://src.fedoraproject.org/rpms/coreutils/c/5440a2d9dbb1f9e1c464e6d71351a3e0a1714660)? They didn't yet package the binary in `-1`.

**Comment by phagara** [comment]
Just noting the last commit done before submitting GSoC final evaluation as required by the [work product submission guidelines](https://developers.google.com/open-source/gsoc/help/work-product), since this pull request is unlikely to get merged before the submission deadline (can't rush a proper security review).

```
commit 8ee6220b430336649d2517bf606bed7a3618795f
Author: Patrik Hagara <patrihagar@gmail.com>
Date:   Fri Aug 25 14:09:49 2017 +0200

    readme: better SRK pw change instructions
```

**Comment by marmarek** [comment]
I've done first pass of the review. Looks good. But before merging, I'd like to test it at least.

**Comment by phagara** [comment]
@marmarek: not to sound impatient, but I'm curious whether you're still way too busy fixing R4.0 release candidates or has this simply fallen off your radar? :)

**Comment by marmarek** [comment]
To be honest, both... I may find some time during freeze before 4.0rc3.

**Comment by phagara** [comment]
Alright, thanks for the update!

**Comment by marmarek** [comment]
Ok, I've finally tested it and found some problems:

### anti-evil-maid-tpm-setup fail with `Bad memory index`

anti-evil-maid-tpm-setup fail with:
```
[root@dom0 user]# anti-evil-maid-tpm-setup -z
anti-evil-maid-tpm-setup: Taking ownership of the TPM...
anti-evil-maid-tpm-setup: Creating TPM ID...
Tspi_NV_DefineSpace failed: 0x00000002 - layer=tpm, code=0002 (2), Bad memory index
```

When I've changed `TPM_ID_INDEX` to `0x7562` (cut to 4 hex digits), it works. Then the same for `TPM_FRESHNESS_INDEX` in `anti-evil-maid-lib`. Is it just arbitrary number, or those indexes have some meaning?

Additional info (`tpm_nvinfo` output): https://gist.github.com/marmarek/e482c765c75fca33337d2a307bd8b0b9

### cryptsetup missing in initramfs
```
/sbin/anti-evil-maid-unseal: line 96: cryptsetup: command not found
```

Adding it to module-setup.sh fixes the problem. Apparently dracut's crypt module use `systemd-cryptsetup`...

### Unsealing freshness token fails

```
anti-evil-maid-unseal: Unsealing freshness token...
Unable to write output file
anti-evil-maid-unseal: Freshness token unsealing failed!
```

This was the first boot after installation, so failed unslealing is expected. But the message could be improved. Or example message added to README.

-----
[unrelated] on my machine I needed newer tboot

Already discussed on qubes-users. Upgrading to tboot-1.9.6 helps on Thinkpad t460p. I see tboot sources are now signed by its developer. So it should be easier to build (slightly more) trustworthy package.

**Comment by marmarek** [comment]
Besides the above minor problems, works great!

**Comment by phagara** [comment]
> **anti-evil-maid-tpm-setup fail with `Bad memory index`**
> Is it just arbitrary number, or those indexes have some meaning?

Yes, it's just an arbitrary number (`0x41454d` used for freshness NVRAM area is the string "AEM" in ASCII hex, while the TPM ID NVRAM index `0x517562` is simply "Qub"[es]). Weird that it does not work with your TPM, mine (made by STM) seems to support 6-byte NVRAM index addressing.

> Additional info (tpm_nvinfo output)

Sadly, that does not provide any useful info for figuring out why you cannot define a 3-byte addressed NVRAM index. AFAIK, there is no way to get a list of supported NVRAM index ranges either. :(

> **cryptsetup missing in initramfs**

Hm, I'm pretty sure this worked when I tried this with R4.0-rc1. Luckily, this one is trivial to fix.

> **Unsealing freshness token fails**
> This was the first boot after installation, so failed unslealing is expected. But the message could be improved. Or example message added to README.

Since this message is displayed without the machine being in a trustworthy state (ie. an evil maid could easily alter it) and there is no unspoofable trivial means of probing whether this is the first boot after AEM installation... What would you propose we do? (I'm leaning towards just putting the error message into installation step 4 of README.)

**Comment by marmarek** [comment]
> Yes, it's just an arbitrary number (0x41454d is the string "AEM" in ASCII hex). Weird that it does not work with your TPM, mine (made by STM) seems to support 6-byte NVRAM index addressing.

Does 2-byte index works on your TPM? If so, I propose to change this, to cover more hardware. Mine is Infineon.

> Since this message is displayed without the machine being in a trustworthy state (ie. an evil maid could easily alter it) and there is no unspoofable trivial means of probing whether this is the first boot after AEM installation... What would you propose we do? (I'm leaning towards just putting the error message into installation step 4 of README.)

Well, the message doesn't need to be unspoofable. I'd add additional sentence there, like "If this is the first boot after AEM installation, it is expected". And add example output to the README.
I was thinking about some flag file on AEM stick, but it's a bad idea for read-only one...

BTW You mention using SD card for AEM. I haven't seen any machine capable booting from SD card (but tested mostly on thinkpads...). Does it work for you?

**Comment by phagara** [comment]
>> Yes, it's just an arbitrary number (0x41454d is the string "AEM" in ASCII hex). Weird that it does not work with your TPM, mine (made by STM) seems to support 6-byte NVRAM index addressing.
>>
> Does 2-byte index works on your TPM? If so, I propose to change this, to cover more hardware. Mine is Infineon.

Yes, defining 2-byte addressed indices work for me.

>> Since this message is displayed without the machine being in a trustworthy state (ie. an evil maid could easily alter it) and there is no unspoofable trivial means of probing whether this is the first boot after AEM installation... What would you propose we do? (I'm leaning towards just putting the error message into installation step 4 of README.)
>>
> Well, the message doesn't need to be unspoofable. I'd add additional sentence there, like "If this is the first boot after AEM installation, it is expected". And add example output to the README.

Sounds good.

> I was thinking about some flag file on AEM stick, but it's a bad idea for read-only one...

And would further increase code complexity.

> BTW You mention using SD card for AEM. I haven't seen any machine capable booting from SD card (but tested mostly on thinkpads...). Does it work for you?

Thinkpads seem to have that broken on purpose & it's a huge pain sometimes (maybe fixable with coreboot/libreboot, haven't tried yet). Booting from an SD card always worked fine for me on other laptop brands though (Asus, HP, ...).

**Comment by marmarek** [comment]
> Thinkpads seem to have that broken on purpose & it's a huge pain sometimes (maybe fixable with coreboot/libreboot, haven't tried yet).

/me getting another thinkpad from the stack
Nope, x230 + coreboot can't do that either.

**Comment by phagara** [comment]
Let me know whether these changes look good to you.

**Review by marmarek — APPROVED** [review]

**Comment by marmarek** [comment]
Thank you, and sorry for extremely long waiting time!

Package uploaded to testing repository: https://github.com/QubesOS/updates-status/issues/405
@andrewdavidwong do we want some announcement (on any channel(s))?

**Comment by andrewdavidwong** [comment]
Perhaps @phagara would like to make the announcement?

We don't typically make feature-specific announcements, but we certainly can if you think it's merited.

**Comment by phagara** [comment]
> Thank you, and sorry for extremely long waiting time!

Thank you too, and don't worry about the delay! Everyone knows it's been crazy on all fronts pretty much the whole time (Xen security, CPU bugs, major issues with R4.0 RCs; just to mention a few).

> We don't typically make feature-specific announcements, but we certainly can if you think it's merited.

I'd say it should be done before the package hits stable repos, just to let the current AEM users know they'll need to re-do some of the setup steps (to create the TPM NVRAM areas) and only then re-provision their AEM media.

Alternatively, we can put that info into post-installation RPM scriptlet so that users see it while updating the package (this might even be the better option, since not everyone reads the mailing lists).

**Comment by marmarek** [comment]
> We don't typically make feature-specific announcements, but we certainly can if you think it's merited.

It doesn't necessarily need to be "standard announcement", it can be just email to qubes-users, or such.

As for RPM scriptlet, note that we don't support in-place 3.2->4.0 upgrade anyway, so there are probably very few people using AEM on 4.0 right now, and needing such upgrade note.

**Comment by andrewdavidwong** [comment]
I think it would be best for @phagara to write the announcement.

**Comment by andrewdavidwong** [comment]
> I'd say it should be done before the package hits stable repos, just to let the current AEM users know they'll need to re-do some of the setup steps (to create the TPM NVRAM areas) and only then re-provision their AEM media.

I'm not familiar enough with AEM to know what this means. (I've never gotten it to work on any of my machines, so I've never used it.) It looks like there's quite a lot of work and discussion in this PR that I haven't been following closely, so I'm not in a position to explain what's going on here to the userbase. If you want to sketch out some notes or a first draft, I'd be happy to help revise it.

**Pull request merged**
