### PR TITLE
Fully automated resealing during boot, compatibility with portable Qubes, all flags auto detected, installer rewritten, cruft removed

### PR DESCRIPTION
**Pull request by rustybird**
Closes QubesOS/qubes-issues#1035.

`git log --find-renames --ignore-all-space` heartily recommended :)

### CODE REVIEW

**Comment by marmarek** [comment]
Wow, this is massive! And impressive!
I think this worth changing version to 3.0.0.
Also it worth sending some announcement to qubes-users mailing list - at least because of changed usage (secret to seal location). Do you want to send it?

Also probably a good idea to note somewhere in the documentation that the secret is stored clear text on encrypted root filesystem. It shouldn't be a problem in normal operation, but users should be aware of this - for example when forced to reveal LUKS passphrase, the AEM secret would also be compromised.

In the meantime I'll do some simple tests and upload the package(s) to current-testing repository.

**Comment by rustybird** [comment]
Thanks! Sorry for dropping it all in one big PR, by the time I had finally figured out a clean design it was fully implemented. :)

Sure, I'll write a post to qubes-users today or tomorrow.

Rebased against master, and added two small commits on top, one of them documenting the thing about not-yet-sealed secret storage

**Comment by marmarek** [comment]
Ow, I've already committed some fixes on top of it... Ok, I'll rebase
them...

Also I can't get `anti-evil-maid-install` to work - it doesn't copy TPM
data. I have an impression that synctpms function mixes up
`$TPMS_DIR/$id` with `$AEM_DIR`, but I'm not sure yet. Or maybe
`anti-evil-maid-seal` should be executed before
`anti-evil-maid-install`? But that won't work without
`/run/anti-evil-maid-seal`...

Also probably worth a note that path
`/var/lib/anti-evil-maid/anti-evil-maid` has in fact device label as the
last component (right?).

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rustybird** [comment]
> Ow, I've already committed some fixes on top of it... Ok, I'll rebase them...

Oops, sorry. I'm interested in your fixes, can you push them to a branch in marmarek/?

> Also I can't get `anti-evil-maid-install` to work - it doesn't copy TPM data. I have an impression that synctpms function mixes up `$TPMS_DIR/$id` with `$AEM_DIR`

`$AEM_DIR` would be where the not-yet-sealed secrets are stored. But there was a bug in `synctpms`; fix pushed.

> Or maybe `anti-evil-maid-seal` should be executed before `anti-evil-maid-install`?

Nope

> But that won't work without `/run/anti-evil-maid-seal`...

Oh it will if you run it manually in a terminal, the check for  `/run/anti-evil-maid-seal` is done only by the systemd unit.

> Also probably worth a note that path `/var/lib/anti-evil-maid/anti-evil-maid` has in fact device label as the last component (right?).

Yes, still got to document using multiple AEM devices without complicating the README too much.

**Comment by marmarek** [comment]
On Mon, Aug 03, 2015 at 04:26:48AM -0700, Rusty Bird wrote:

> > Ow, I've already committed some fixes on top of it... Ok, I'll rebase them...
> 
> Oops, sorry. I'm interested in your fixes, can you push them to a branch in marmarek/?

Sure, `rework2` branch.

> > Also I can't get `anti-evil-maid-install` to work - it doesn't copy TPM data. I have an impression that synctpms function mixes up `$TPMS_DIR/$id` with `$AEM_DIR`
> 
> `$AEM_DIR` would be where the not-yet-sealed secrets are stored. But there was a bug in `synctpms`; fix pushed.

Ok, will check this out.

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rustybird** [comment]
> Sure, `rework2` branch.

Thanks, these are great! Very sorry about the missing `-r` in `anti-evil-maid-check-mount-devs`, I hadn't realized there's padding for major:minor. Cherry-picked and pushed all your fixes, plus two more `-r` related commits.

**Comment by rustybird** [comment]
I'll be spending a couple more days on the installer before writing the qubes-users post

**Comment by rustybird** [comment]
Okay, `anti-evil-maid-install` makes external AEM devices bootable again, and `anti-evil-maid-seal.service` seals only for the device that failed to unseal.

Also retrying the SRK password prompt now.

The correct workflow for an external device still needs to be documented. `README` once had a paragraph about removing the internal boot partition from `/etc/fstab`, but it was phrased more in terms of convenience, when the real issue is to never ever mount an untrusted filesystem in dom0, right?

**Comment by marmarek** [comment]
On Sat, Aug 15, 2015 at 08:10:38AM -0700, Rusty Bird wrote:

> Okay, `anti-evil-maid-install` makes external AEM devices bootable again, and `anti-evil-maid-seal.service` seals only for the device that failed to unseal.
> 
> Also retrying the SRK password prompt now.

:)

> The correct workflow for an external device still needs to be
> documented. `README` once had a paragraph about removing the internal
> boot partition from `/etc/fstab`, but it was phrased more in terms of
> convenience, when the real issue is to never ever mount an untrusted
> filesystem in dom0, right?

Yes, exactly.

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rustybird** [comment]
Ping... ;)

Anything essential still missing?

**Comment by marmarek** [comment]
On Sun, Sep 06, 2015 at 11:28:36AM -0700, Rusty Bird wrote:

> Ping... ;)
> 
> Anything essential still missing?

No, just focused on final polishing of R3.0...

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
One more issue... When the AEM device is discovered late, it may happen
that anti-evil-maid-unseal service is already called (and detects no AEM
device). I've done a simple test having magnetic HDD (which requires
some time to spin up) as AEM device.
I think this may be solved by waiting some time if no AEM device is
present at first.

Other than that, I've found some minor issues in
`anti-evil-maid-install`, I'll push commit(s) to `rework3` branch in my
repo.

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rustybird** [comment]
> One more issue... When the AEM device is discovered late, it may happen that anti-evil-maid-unseal service is already called (and detects no AEM device). I've done a simple test having magnetic HDD (which requires some time to spin up) as AEM device. I think this may be solved by waiting some time if no AEM device is present at first.

Shouldn't the `udevadm trigger` and `udevadm settle` in `anti-evil-maid-unseal` take care of this? And the HDD be spun up already because it was booted from?

> Other than that, I've found some minor issues in `anti-evil-maid-install`, I'll push commit(s) to `rework3` branch in my repo.

I don't understand `minor: handle already existing /var/lib/tpms`. How can /var/lib/tpms already exist in the initrd?

The other three commits I've cherry picked and pushed, with a few changes in additional commits. In particular, `Consider all LUKS devices when checking if the device is "external"` made `external()` _always_ return success, so our score is now 1:1 in the blowing away internal boot partitions championship :D

**Comment by marmarek** [comment]
On Mon, Oct 05, 2015 at 06:21:13AM -0700, Rusty Bird wrote:

> > One more issue... When the AEM device is discovered late, it may happen that anti-evil-maid-unseal service is already called (and detects no AEM device). I've done a simple test having magnetic HDD (which requires some time to spin up) as AEM device. I think this may be solved by waiting some time if no AEM device is present at first.
> 
> Shouldn't the `udevadm trigger` and `udevadm settle` in `anti-evil-maid-unseal` take care of this?

No, this only ensure that devices already detected by the kernel are
processed. Especially the root device is detected later when also on
external USB disk...

> And the HDD be spun up already because it was booted from?

This isn't always true, becacuse:
- when kernel driver is loaded, USB controller may be reset, so the
  devices connected to it
- AEM disk may be not the same as boot disk

> > Other than that, I've found some minor issues in `anti-evil-maid-install`, I'll push commit(s) to `rework3` branch in my repo.
> 
> I don't understand `minor: handle already existing /var/lib/tpms`. How can /var/lib/tpms already exist in the initrd?

When you call that script from running system (not initramfs) to
manually unseal the data, it will break /var/lib/tpms (namely will
create /var/lib/tpms/tpms, which will cause errors later, because not
existing /var/lib/tpms/tpms/system.data). I know, shouldn't happen in
normal use case.

> The other three commits cherry I've picked and pushed, with a few changes in additional commits. In particular, `Consider all LUKS devices when checking if the device is "external"` made `external()` _always_ return success, so our score is now 1:1 in the blowing away internal boot partitions championship :D

:D

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rustybird** [comment]
Okay, now looping until `/dev/disk/by-label/aem*` appears (or the systemd default timeout kicks in), and handling existing directories. (I didn't know that `cp -Tr` works with _nonempty_ target directories. Pretty neat, it's like a miniature rsync.)

**Comment by marmarek** [comment]
Uploaded to current-testing :)

## 

Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Pull request merged**
